### PR TITLE
Fix/workaround for #204

### PR DESCRIPTION
**Pull request by sander1988**
- v3.1.2: Fix/workaround for #204 - https://github.com/jm-73/Indego/issues/204

### CODE REVIEW

**Comment by Rosi2143** [comment]
Hi,

can you please rebase the MR to the latest version of "develop" - now the tests are working again.

Thanks.

**Comment by sander1988** [comment]
> Hi,
> 
> can you please rebase the MR to the latest version of "develop" - now the tests are working again.
> 
> Thanks.

I have merged everything and **also applied a fix to setup.py**. 

There was a bug in the version load logic as the import of version.py also imports the package (__ init __.py) which imports the pip deps. That would fail as setup.py didn't yet completed installing them.

This pull request shows more changes than I would have expected. But it seems the master of this repo is ahead of the develop branch, that's why. Is that correct?

**Comment by Rosi2143** [comment]
Hi @sander1988,

yes - I changes some settings to make tests run again correctly with the new loging method - and did this first on master.
While beeing at it I also changes some typos, flake8 warnings and format issues - which I should have done only on develop 😞.

Thanks for your changes - they look good.

I'm still looking for a nice way to get the "token" - do you have an easy way to get it?

**Comment by sander1988** [comment]
> I'm still looking for a nice way to get the "token" - do you have an easy way to get it?
@Rosi2143 - Yes that's probably possible. Can you drop a message in Discord with some details about what you are trying to achieve?

**Pull request merged**
