### PR TITLE
Adds OAuth (Bosch SingleKey ID support) 

### PR DESCRIPTION
**Pull request by sander1988**
- Added OAuth (Bosch SingleKey ID support) #116 .
- Improved logging output.
- Added call to retrieve the available mowers/serial a the account.

Note: I have only tested the calls used by the HA integration (https://github.com/jm-73/Indego/) .

### CODE REVIEW

**Comment by buennerbernd** [comment]
@sander1988 It looks like you got the Indego running again.
I'm trying the same for the FHEM Indego module.
I have some questions how you solved this.
How did you get the first bearer token?
What is the URL to start the login? Any headers needed?

Thank you,
Stefan.

**Comment by sander1988** [comment]
> @sander1988 It looks like you got the Indego running again. I'm trying the same for the FHEM Indego module. I have some questions how you solved this. How did you get the first bearer token? What is the URL to start the login? Any headers needed?
> 
> Thank you, Stefan.

Please check this issue: https://github.com/jm-73/Indego/issues/171

This is what we reverse engineered from the Indego Android app. That's what I used to implement this update.

**Comment by buennerbernd** [comment]
> Please check this issue: [jm-73/Indego#171](https://github.com/jm-73/Indego/issues/171)
> 
> This is what we reverse engineered from the Indego Android app. That's what I used to implement this update.

Thank you, this was helpful. I have this running in Postman now using the Bearer Token.
How can I use the refresh_token?

Edit:
My educated guess was:
https://prodindego.b2clogin.com/prodindego.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/token?grant_type=refresh_token&refresh_token=eyJ...

Works!

**Comment by sander1988** [comment]
I just added a small update to version 2.2.0 . This adds the option **raise_request_exceptions**. This way we can detect these kind of errors in the applications (like HA) make some decisions based on it. 

For example to delay the next update, to prevent update loops. I have seen this issues where a 502 on the Bosch side caused the client to do > 10 requests a second.

**Comment by jm-73** [comment]
Same here: would be great to do pull requests to the develop branch. I always do this when i develop new features or trying to fix bugs.

**Comment by sander1988** [comment]
> Same here: would be great to do pull requests to the develop branch. I always do this when i develop new features or trying to fix bugs.

You can the PR right? As you are the project owner.

**Comment by jm-73** [comment]
> > Same here: would be great to do pull requests to the develop branch. I always do this when i develop new features or trying to fix bugs.
> 
> You can the PR right? As you are the project owner.

I dont know how.

**Comment by sander1988** [comment]
> > > Same here: would be great to do pull requests to the develop branch. I always do this when i develop new features or trying to fix bugs.
> > 
> > 
> > You can the PR right? As you are the project owner.
> 
> I dont know how.

Ok, I have changed it.

**Pull request merged**
